/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Counter.java
 *
 * Created on 26-apr-2013, 9:04:52
 */
package othello;

import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.Serializable;

/**
 *
 * @author jrvdvyve
 */
public class Counter extends javax.swing.JPanel implements Serializable, PropertyChangeListener {

    private int number;
    private int stateToCount;

    public synchronized int getNumber() {
        return number;
    }

    public synchronized void setNumber(int number) {
        this.number = number;
        jLabel1.setText(number + "");
    }

    public synchronized int getStateToCount() {
        return stateToCount;
    }

    public synchronized void setStateToCount(int stateToCount) {
        this.stateToCount = stateToCount;
    }

    /** Creates new form Counter */
    public Counter() {
        initComponents();
        setNumber(0);

    }

    public synchronized void increment() {
        setNumber(getNumber() + 1);
    }

    public synchronized void decrement() {
        setNumber(getNumber() - 1);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(76, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void propertyChange(PropertyChangeEvent evt) {

        if ("state".equals(evt.getPropertyName())) {
            synchronized (this) {
                int oldValue = Integer.parseInt(evt.getOldValue().toString());
                int newValue = Integer.parseInt(evt.getNewValue().toString());
                if (oldValue == stateToCount && newValue != stateToCount) {
                    decrement();
                } else if (oldValue != stateToCount && newValue == stateToCount) {
                    increment();
                }

                jLabel1.setText("" + number);
            }
        }
    }
}
