/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * OthelloPanel.java
 *
 * Created on 26-apr-2013, 8:43:37
 */
package othello;

import java.beans.PropertyChangeEvent;
import javax.swing.border.TitledBorder;

/**
 *
 * @author jrvdvyve
 */
public class OthelloPanel extends javax.swing.JPanel {

    /** Creates new form OthelloPanel */
    public OthelloPanel() {
        initComponents();
        //EMPTY
        counter1.setStateToCount(0);
        counter1.setBorder(new TitledBorder("Empty"));
        counter1.setNumber(16);
        
        //WHITE
        counter2.setStateToCount(1);
        counter2.setBorder(new TitledBorder("White"));
        //BLACK
        counter3.setStateToCount(-1);
        counter3.setBorder(new TitledBorder("Black"));
        
        OthelloPiece[] pieces = {
            othelloPiece1, othelloPiece2, othelloPiece3, othelloPiece4, othelloPiece5,
            othelloPiece6, othelloPiece7, othelloPiece8, othelloPiece9, othelloPiece10, othelloPiece11, othelloPiece12,
            othelloPiece13, othelloPiece14, othelloPiece15, othelloPiece16
                
        };
        
        for (OthelloPiece p : pieces) {
            p.addPropertyChangeListener(counter1);
            p.addPropertyChangeListener(counter2);
            p.addPropertyChangeListener(counter3);
        }     
            
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        othelloPiece1 = new othello.OthelloPiece();
        othelloPiece2 = new othello.OthelloPiece();
        othelloPiece3 = new othello.OthelloPiece();
        othelloPiece4 = new othello.OthelloPiece();
        othelloPiece5 = new othello.OthelloPiece();
        othelloPiece6 = new othello.OthelloPiece();
        othelloPiece7 = new othello.OthelloPiece();
        othelloPiece8 = new othello.OthelloPiece();
        othelloPiece9 = new othello.OthelloPiece();
        othelloPiece10 = new othello.OthelloPiece();
        othelloPiece11 = new othello.OthelloPiece();
        othelloPiece12 = new othello.OthelloPiece();
        othelloPiece13 = new othello.OthelloPiece();
        othelloPiece14 = new othello.OthelloPiece();
        othelloPiece15 = new othello.OthelloPiece();
        othelloPiece16 = new othello.OthelloPiece();
        counter1 = new othello.Counter();
        counter2 = new othello.Counter();
        counter3 = new othello.Counter();

        javax.swing.GroupLayout othelloPiece1Layout = new javax.swing.GroupLayout(othelloPiece1);
        othelloPiece1.setLayout(othelloPiece1Layout);
        othelloPiece1Layout.setHorizontalGroup(
            othelloPiece1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        othelloPiece1Layout.setVerticalGroup(
            othelloPiece1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout othelloPiece2Layout = new javax.swing.GroupLayout(othelloPiece2);
        othelloPiece2.setLayout(othelloPiece2Layout);
        othelloPiece2Layout.setHorizontalGroup(
            othelloPiece2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        othelloPiece2Layout.setVerticalGroup(
            othelloPiece2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout othelloPiece3Layout = new javax.swing.GroupLayout(othelloPiece3);
        othelloPiece3.setLayout(othelloPiece3Layout);
        othelloPiece3Layout.setHorizontalGroup(
            othelloPiece3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        othelloPiece3Layout.setVerticalGroup(
            othelloPiece3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout othelloPiece4Layout = new javax.swing.GroupLayout(othelloPiece4);
        othelloPiece4.setLayout(othelloPiece4Layout);
        othelloPiece4Layout.setHorizontalGroup(
            othelloPiece4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        othelloPiece4Layout.setVerticalGroup(
            othelloPiece4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout othelloPiece5Layout = new javax.swing.GroupLayout(othelloPiece5);
        othelloPiece5.setLayout(othelloPiece5Layout);
        othelloPiece5Layout.setHorizontalGroup(
            othelloPiece5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        othelloPiece5Layout.setVerticalGroup(
            othelloPiece5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout othelloPiece6Layout = new javax.swing.GroupLayout(othelloPiece6);
        othelloPiece6.setLayout(othelloPiece6Layout);
        othelloPiece6Layout.setHorizontalGroup(
            othelloPiece6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        othelloPiece6Layout.setVerticalGroup(
            othelloPiece6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout othelloPiece7Layout = new javax.swing.GroupLayout(othelloPiece7);
        othelloPiece7.setLayout(othelloPiece7Layout);
        othelloPiece7Layout.setHorizontalGroup(
            othelloPiece7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        othelloPiece7Layout.setVerticalGroup(
            othelloPiece7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout othelloPiece8Layout = new javax.swing.GroupLayout(othelloPiece8);
        othelloPiece8.setLayout(othelloPiece8Layout);
        othelloPiece8Layout.setHorizontalGroup(
            othelloPiece8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        othelloPiece8Layout.setVerticalGroup(
            othelloPiece8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout othelloPiece9Layout = new javax.swing.GroupLayout(othelloPiece9);
        othelloPiece9.setLayout(othelloPiece9Layout);
        othelloPiece9Layout.setHorizontalGroup(
            othelloPiece9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        othelloPiece9Layout.setVerticalGroup(
            othelloPiece9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout othelloPiece10Layout = new javax.swing.GroupLayout(othelloPiece10);
        othelloPiece10.setLayout(othelloPiece10Layout);
        othelloPiece10Layout.setHorizontalGroup(
            othelloPiece10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        othelloPiece10Layout.setVerticalGroup(
            othelloPiece10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout othelloPiece11Layout = new javax.swing.GroupLayout(othelloPiece11);
        othelloPiece11.setLayout(othelloPiece11Layout);
        othelloPiece11Layout.setHorizontalGroup(
            othelloPiece11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        othelloPiece11Layout.setVerticalGroup(
            othelloPiece11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout othelloPiece12Layout = new javax.swing.GroupLayout(othelloPiece12);
        othelloPiece12.setLayout(othelloPiece12Layout);
        othelloPiece12Layout.setHorizontalGroup(
            othelloPiece12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        othelloPiece12Layout.setVerticalGroup(
            othelloPiece12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout othelloPiece13Layout = new javax.swing.GroupLayout(othelloPiece13);
        othelloPiece13.setLayout(othelloPiece13Layout);
        othelloPiece13Layout.setHorizontalGroup(
            othelloPiece13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        othelloPiece13Layout.setVerticalGroup(
            othelloPiece13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout othelloPiece14Layout = new javax.swing.GroupLayout(othelloPiece14);
        othelloPiece14.setLayout(othelloPiece14Layout);
        othelloPiece14Layout.setHorizontalGroup(
            othelloPiece14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        othelloPiece14Layout.setVerticalGroup(
            othelloPiece14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout othelloPiece15Layout = new javax.swing.GroupLayout(othelloPiece15);
        othelloPiece15.setLayout(othelloPiece15Layout);
        othelloPiece15Layout.setHorizontalGroup(
            othelloPiece15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        othelloPiece15Layout.setVerticalGroup(
            othelloPiece15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout othelloPiece16Layout = new javax.swing.GroupLayout(othelloPiece16);
        othelloPiece16.setLayout(othelloPiece16Layout);
        othelloPiece16Layout.setHorizontalGroup(
            othelloPiece16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        othelloPiece16Layout.setVerticalGroup(
            othelloPiece16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(othelloPiece1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(othelloPiece2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(othelloPiece3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(othelloPiece4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(othelloPiece5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(othelloPiece6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(othelloPiece7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(othelloPiece8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(othelloPiece13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(othelloPiece14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(othelloPiece15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(othelloPiece16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(othelloPiece9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(othelloPiece10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(othelloPiece11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(othelloPiece12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(counter2, 0, 0, Short.MAX_VALUE)
                    .addComponent(counter3, 0, 0, Short.MAX_VALUE)
                    .addComponent(counter1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(counter1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(counter2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(counter3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(othelloPiece3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(othelloPiece2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(othelloPiece1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(othelloPiece4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(othelloPiece5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(othelloPiece6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(othelloPiece7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(othelloPiece8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(othelloPiece9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(othelloPiece10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(othelloPiece11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(othelloPiece12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(othelloPiece13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(othelloPiece14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(othelloPiece15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(othelloPiece16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(89, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private othello.Counter counter1;
    private othello.Counter counter2;
    private othello.Counter counter3;
    private othello.OthelloPiece othelloPiece1;
    private othello.OthelloPiece othelloPiece10;
    private othello.OthelloPiece othelloPiece11;
    private othello.OthelloPiece othelloPiece12;
    private othello.OthelloPiece othelloPiece13;
    private othello.OthelloPiece othelloPiece14;
    private othello.OthelloPiece othelloPiece15;
    private othello.OthelloPiece othelloPiece16;
    private othello.OthelloPiece othelloPiece2;
    private othello.OthelloPiece othelloPiece3;
    private othello.OthelloPiece othelloPiece4;
    private othello.OthelloPiece othelloPiece5;
    private othello.OthelloPiece othelloPiece6;
    private othello.OthelloPiece othelloPiece7;
    private othello.OthelloPiece othelloPiece8;
    private othello.OthelloPiece othelloPiece9;
    // End of variables declaration//GEN-END:variables
}
